version: "3.3"
services:
  spark-master:
    image: spark:1.0.0
    ports:
      - "7077:7077"
      - "9090:8080"
      - "4040:4040"
      - "10015:10015"
    volumes:
      - ./apps:/apps
      - ./data:/data
      - ./drivers:/drivers
      - ./logs:/opt/spark/logs
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
      - HIVE_SERVER2_THRIFT_PORT=10015
  spark-worker-a:
    image: spark:1.0.0
    ports:
      - "7000:7000"
      - "9091:8080"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=4G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=512MB
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
      - ./apps:/apps
      - ./data:/data
      - ./drivers:/drivers
      - ./logs:/opt/spark/logs
  spark-worker-b:
    image: spark:1.0.0
    ports:
      - "7001:7000"
      - "9092:8080"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=4G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=512MB
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
      - ./apps:/apps
      - ./data:/data
      - ./drivers:/drivers
      - ./logs:/opt/spark/logs
